export default {
    LOAD_JSON_API_ENTITY_DATA: 'LOAD_JSON_API_ENTITY_DATA',

    ADD_RELATIONSHIP_TO_ENTITY: 'ADD_RELATIONSHIP_TO_ENTITY',
    REMOVE_RELATIONSHIP_FROM_ENTITY: 'REMOVE_RELATIONSHIP_FROM_ENTITY',
    SET_RELATIONSHIP_ON_ENTITY: 'SET_RELATIONSHIP_ON_ENTITY',
    CLEAR_RELATIONSHIP_ON_ENTITY: 'CLEAR_RELATIONSHIP_ON_ENTITY',

    UPDATE_ENTITY: 'UPDATE_ENTITY',
    UPDATE_ENTITIES_META: 'UPDATE_ENTITIES_META',
    UPDATE_ENTITY_META: 'UPDATE_ENTITY_META',

    REMOVE_ENTITY: 'REMOVE_ENTITY',
    CLEAR_ENTITY_TYPE: 'CLEAR_ENTITY_TYPE',
};
