export const actionNames = {
    LOAD_JSON_API_ENTITY_DATA: 'LOAD_JSON_API_ENTITY_DATA',
    ADD_RELATIONSHIP_TO_ENTITY: 'ADD_RELATIONSHIP_TO_ENTITY',
    REMOVE_RELATIONSHIP_FROM_ENTITY: 'REMOVE_RELATIONSHIP_FROM_ENTITY',
    UPDATE_ENTITY: 'UPDATE_ENTITY',
    UPDATE_ENTITIES_META: 'UPDATE_ENTITIES_META',
};
