export const actionNames = {
    INSERT_OR_UPDATE_ENTITIES: "INSERT_OR_UPDATE_ENTITIES",
    ADD_RELATIONSHIP_TO_ENTITY: "ADD_RELATIONSHIP_TO_ENTITY",
    REMOVE_RELATIONSHIP_FROM_ENTITY: "REMOVE_RELATIONSHIP_FROM_ENTITY"
}
